# version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: flashcard_mongo_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
    #Persists MongoDB data in a named volume mongodb_data to ensure data is not lost when the container restarts.
    volumes:
      - mongodb_data:/data/db
#Defineing a named volume mongodb_data for persistent storage
volumes:
  mongodb_data:
